mapbox/mapbox-vision-android-teaser

app/.gitignore
app/build.gradle
app/generate-token.gradle
app/src/main/java/com/mapbox/vision/examples/DemoApplication.kt
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt
build.gradle

Now you'll just need to add `app/fabric.properties` to repo to make it work.

Add Crashlytics

---

app/build.gradle
gradle/versions.gradle

New features:
Safety mode
Line departure
Calibration progress

Release 0.1.2

---

app/src/main/java/com/mapbox/vision/examples/activity/ar/ArMapActivity.kt

Fix fir https://github.com/mapbox/cv-assist/issues/682

Fix crash at offline Ar Map activity.

---

app/build.gradle
settings.gradle

Fix settings.gradle

---

app/build.gradle
app/src/androidTest/java/com/mapbox/vision/examples/ExampleInstrumentedTest.kt
app/src/main/java/com/mapbox/vision/examples/DemoApplication.kt
app/src/main/java/com/mapbox/vision/examples/SafetyModeView.kt
app/src/main/java/com/mapbox/vision/examples/ScoreProgressView.kt
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArMapActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/map/MapActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_map.xml
app/src/main/res/layout/score_progress_view.xml
gradle.properties
gradle/versions.gradle

Migration to androidx

---

app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt

Checks:
Linked issues:
closes #78

Foreground_service permission fix

---

app/build.gradle
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArMapActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
app/src/main/java/com/mapbox/vision/examples/activity/map/MapActivity.kt
app/src/main/res/layout/activity_ar_map.xml
app/src/main/res/layout/activity_map.xml
gradle/versions.gradle

Checks:
Linked issues:
closes #80

Refactoring to use updated telemetry and core libs

---

app/src/main/java/com/mapbox/vision/examples/SafetyModeView.kt
app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
gradle/versions.gradle

closes [1296](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1296)

Fix warnings drawing on safety mode

---

app/src/main/java/com/mapbox/vision/examples/SafetyModeView.kt

1. calculation fixed
2. draw distance logic removed
closes #84

Fix collision bounds calculation

---

app/build.gradle
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArMapActivity.kt
gradle/versions.gradle

1. Telemetry lib downgrade 4.5.1 -> 4.4.1
2. LocationComponent added on the map
closes [1357](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1357)
closes [1364](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1364)

Knn teaser fixes

---

app/build.gradle
app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt

The merge doesn't contain changes from the 'log-excepton-board-name'

Dev with needed changes to master

---

app/src/main/java/com/mapbox/vision/examples/FpsPerformanceView.kt
app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/view_fps_performance.xml

Added average fps
closes [104](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision-android-teaser/104)

Teaser debug panel enhancement.

---

app/build.gradle
gradle/versions.gradle

closes [1445](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1445)

Navigation lib update 0.40.0 -> 0.41.0

---

CHANGELOG.md
gradle/versions.gradle

Teaser release 0.7.1

---

CHANGELOG.md
gradle/versions.gradle

release version 0.8.0

---

.gitignore
docs/smoke-test.md
scripts/smoke-test/teaser_smoke_test.py
scripts/smoke-test/utils/android_view_helper.py
scripts/smoke-test/utils/command_runner.py
scripts/smoke-test/utils/device_executor.py
scripts/smoke-test/utils/folder_helper.py

Kas smoke teaser test

---

app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
app/src/main/res/layout/activity_main.xml

Modify teaser to make use of new VisionView API
Linked issues:
[#1631](https://github.com/mapbox/mapbox-vision/pull/1696)

New API of VisionView

---

.gitmodules
app/build.gradle
settings.gradle

Use submodule to import vision and vision android repo.

---

app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
recorder/src/main/java/com/mapbox/vision/recorder/RecordingActivity.kt

Correct lifecycle of VisionView

Correct lifecycle of VisionView

---

app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt

Set vision manager after VisionManager.create()

Set vision manager after VisionManager.create()

---

recorder/build.gradle
replayer/build.gradle
replayer/src/main/java/com/mapbox/vision/replayer/ArReplayNavigationActivity.kt

Release signing config for recorder and replayer

---

common/src/main/java/com/mapbox/vision/common/models/UiSign.kt
common/src/main/java/com/mapbox/vision/common/utils/classification/SignResources.kt

related issue [1789](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1789)

Support Germany and new signs

---

app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt
app/src/main/res/layout/activity_ar_navigation.xml
common/src/main/java/com/mapbox/vision/common/utils/RouteUtils.kt
replayer/src/main/java/com/mapbox/vision/replayer/ArReplayNavigationActivity.kt

Do not merge until fences get merged to Vision

Modify AR activities to make use of AR Fences

---

common/src/main/java/com/mapbox/vision/common/models/UiSign.kt
common/src/main/java/com/mapbox/vision/common/utils/classification/SignResources.kt

Just a quick fix to display European assets for Germany

Use european assets for Germany instead of US.

---

common/src/main/java/com/mapbox/vision/common/BaseVisionActivity.kt
common/src/main/java/com/mapbox/vision/common/view/FpsPerformanceView.kt
common/src/main/res/values/strings.xml

Updated API to check device support. 
Updated mapbox-vision submodule to latest MACE version.

Use updated mapbox-vision

---

app/src/main/kotlin/com/mapbox/vision/teaser/replayer/ArReplayNavigationActivity.kt

Fix crash on return from ArReplayNavigationActivity

Add check if VisionReplayManager is init in ArReplayNavigationActivity

---

app/build.gradle
gradle/versions.gradle

https://square.github.io/leakcanary/

Integrate LeakCanary

---

app/src/main/kotlin/com/mapbox/vision/teaser/view/SafetyModeView.kt

Remove TODO and use correct resolution because it's not hardcoded now.

Update Safety scaling

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/com/mapbox/vision/teaser/MainActivity.kt

Not merge until https://github.com/mapbox/mapbox-vision/pull/2651

[Android] Add reverse landscape orientsation
